// Generated by CoffeeScript 1.7.1
(function() {
  requirejs.config({
    baseUrl: '/',
    paths: {
      jquery: "bower_components/jquery/dist/jquery.min",
      bootstrap: "bower_components/bootstrap/dist/js/bootstrap.min",
      vegas: "bower_components/vegas/dist/jquery.vegas.min",
      header: "modules/header/js/index",
      home: "modules/home/js/index"
    },
    shim: {
      bootstrap: {
        deps: ['jquery'],
        exports: 'bootstrap'
      },
      vegas: {
        deps: ['jquery'],
        exports: 'vegas'
      }
    }
  });

  requirejs(['jquery', 'bootstrap', 'vegas'], function() {
    return requirejs(['header', 'home'], function() {});
  });

}).call(this);
