// Generated by CoffeeScript 1.7.1
(function() {
  (function($) {
    $(function() {
      var time_change_photo;
      time_change_photo = 1000;
      $.vegas("slideshow", {
        backgrounds: [
          {
            src: "img/slider/slider7.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider2.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider3.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider4.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider5.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider6.jpg",
            fade: time_change_photo
          }, {
            src: "img/slider/slider1.jpg",
            fade: time_change_photo
          }
        ]
      })();
    });
  })(jQuery);

}).call(this);
